on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demoacr15072021.azurecr.io
        username: demoacr15072021
        password: ${{ secrets.acr_demoacr15072021_password }}
    
    # - name: Build and push image to ACR
    #   id: build-image
    #   run: |
    #     docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t demoacr072021.azurecr.io/demoaks1:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
    #     docker push demoacr072021.azurecr.io/demoaks1:${{ github.sha }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t demoacr15072021.azurecr.io/azure-vote-front:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push demoacr15072021.azurecr.io/azure-vote-front:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demoaks2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: demoacr15072021.azurecr.io
        container-registry-username: demoacr15072021
        container-registry-password: ${{ secrets.acr_demoacr15072021_password }}
        secret-name: demoaks2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          azure-vote-all-in-one-redis.yaml
        images: |
          demoacr072021.azurecr.io/azure-vote-front:${{ github.sha }}
        imagepullsecrets: |
          demoaks2dockerauth
